network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      addresses: [192.168.3.103/24]
      gateway4: 192.168.3.1
      nameservers:
        addresses: [192.168.3.1, 8.8.8.8]
